version: '3.8'

networks:
  frontend:
    driver: bridge

services:
#frontend-services
  api:
    build: ./api
    container_name: api
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=172.16.1.30
      - INVENTORY_URL=http://inventory.byf5.cloud
      - RECOMMENDATIONS_URL=http://recommendations.byf5.cloud
      - IMAGE_DIRECTORY=${PRODUCT_TYPE}
    dns:
      - 8.8.8.8
    restart: unless-stopped
    networks:
      - frontend
  spa:
    build:
      context: ./spa
      args:
        VITE_APP_GLOBAL_COLOR: "#000"
        VITE_APP_GLOBAL_BACKGROUND_COLOR: "#FFF"
    container_name: spa
    ports:
      - "8081:8080"
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - frontend  
  checkout:
    build: ./checkout
    container_name: checkout
    ports:
      - "8003:8003"
    restart: unless-stopped
    networks:
      - frontend
  spa-dark:
    build:
      context: ./spa
      args:
        VITE_APP_GLOBAL_COLOR: "#FFF"
        VITE_APP_GLOBAL_BACKGROUND_COLOR: "#000"
    container_name: spa-dark
    ports:
      - "8082:8080"
    links:
      - api
    restart: unless-stopped
    

#backend-services
  recommendations:
    build:
      context: .
      dockerfile: ./recommendations/Dockerfile
    container_name: recs
    ports:
      - "8001:8001"
    environment:
      - SEED_FILE=${PRODUCT_TYPE}Products.json
    restart: unless-stopped

  inventory:
    build: ./inventory
    container_name: inv
    ports:
      - "8002:8002"
    restart: unless-stopped


#database
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-seed:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      - SEED_FILE=${PRODUCT_TYPE}Products.json

  
  
  
  
